#!/bin/zsh

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# initial setup
mkdir -p /home/kali/tmp
chmod 755 /home/kali/tmp
mkdir -p /home/kali/srv
chmod 755 /home/kali/srv
ln -s /usr/share/wordlists /home/kali/wordlists 2>/dev/null
mkdir -p /home/kali/srv/peass-ng
chmod 755 /home/kali/srv/peass-ng

# system updating
echo "===== system update ====="
apt-get update
apt-get dist-upgrade
apt-get autoremove

# searchsploit db
echo "===== searchsploit update ====="
searchsploit -u

# update srv files
echo "===== server files update ====="
cd /home/kali/srv

## PEASS-ng
echo "===== peass-ng update ====="
rm peass-ng/linpeas.sh 2>/dev/null
rm peass-ng/winPEAS.bat 2>/dev/null
rm peass-ng/winPEASany.exe 2>/dev/null

releaseHead="browser_download_url.*"
grepOr="\|"

lookup=${releaseHead}"linpeas.sh"
lookup=${lookup}${grepOr}${releaseHead}"winPEAS.bat"
lookup=${lookup}${grepOr}${releaseHead}"winPEASany.exe"

# get latest peass-ng release from github
curl -s https://api.github.com/repos/carlospolop/PEASS-ng/releases/latest \
| grep ${lookup} \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i - -P peass-ng

chmod 666 peass-ng/linpeas.sh
chmod 666 peass-ng/winPEAS.bat 
chmod 666 peass-ng/winPEASany.exe

echo "==== deleting downloads ===="
rm -rfv /home/kali/Downloads/*

echo "==== clearing desktop ===="
rm -rfv /home/kali/Desktop

echo "==== clearing ~/tmp ====="
rm -rfv /home/kali/tmp/*

echo "==== clearing zsh history ===="
fc -p # clear root user history

echo "" > /home/kali/.zsh_history
echo "" > /root/.zshrc

echo "==== snapshot update complete ===="
